# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desenvolvedor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabalha_em',
            old_name='id_projeto',
            new_name='projeto',
        ),
        migrations.RenameField(
            model_name='trabalha_em',
            old_name='email',
            new_name='user',
        ),
    ]
