#*******************************************************************************
#
#    Marcos Vinicius do Carmo Sousa  nº USP: 9298274
#    Matheus Tavares Bernardino      nº USP: 9292987
#
#
#*******************************************************************************


Ep3.class: Ep3.java Simulation.java ProcTable.java BitMap.java Event.java\
EventsList.java PagTable.java PageManagement.java
	rm -f *.class
	javac Ep3.java



.PHONY: clean
clean:
	rm -f *.class *~
