# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=False)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
