# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionalidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('id_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto')),
            ],
        ),
        migrations.AddField(
            model_name='funcionalidades',
            name='id_requisito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisito.Requisito'),
        ),
    ]
