# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisito', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionalidades',
            old_name='id_requisito',
            new_name='requisito',
        ),
        migrations.RenameField(
            model_name='requisito',
            old_name='id_e',
            new_name='projeto',
        ),
    ]
